"""
llm.py
-------
This module provides functionality to interact with the OpenAI API to generate human-friendly explanations for Terraform infrastructure changes.
It securely loads the OpenAI API key from the environment using a .env file and provides a single function for generating explanations via GPT-4o.
"""

import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY is not set in the environment or .env file.")

client = OpenAI(api_key=api_key)


def explain_with_gpt(prompt: str) -> str:
    """
    Generate a human-readable explanation for Terraform infrastructure changes using OpenAI's GPT-4o.

    Args:
        prompt (str): A prompt string describing the Terraform changes to explain.

    Returns:
        str: A human-readable explanation generated by GPT-4o.
    """
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are an expert in cloud infrastructure and Terraform. Provide clear, concise, human-friendly explanations of infrastructure changes."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
        max_tokens=1000
    )
    return response.choices[0].message.content.strip()